import type { Symptom } from './types'

export const symptoms: Symptom[] = [
  {id:'bloating',label:'Barriga estufada',category:'digestao',aliases:['barriga inchada','empachamento','estufamento'],weights:{spleen_qi:2,liver_spleen:1}},
  {id:'fatigue',label:'Cansaço',category:'energia',aliases:['sem energia','fraqueza'],weights:{spleen_qi:1,kidney_yang:1,lung_qi:1,heart_blood:1}},
  {id:'poor_sleep',label:'Sono ruim',category:'sono',aliases:['insônia','durmo mal'],weights:{heart_blood:1,heart_yin:1}},
  {id:'stress',label:'Estresse / irritação',category:'emocional',aliases:['ansiedade','irritado','nervoso'],weights:{liver_spleen:2,liver_stagnation:2,liver_fire:1}},
  {id:'headache',label:'Dor de cabeça',category:'cabeca',aliases:['cefaleia','enxaqueca'],weights:{liver_fire:1,liver_stagnation:1}},
  {id:'constipation',label:'Intestino preso',category:'intestino',aliases:['prisão de ventre','constipação'],weights:{kidney_yin:1,liver_fire:1}},
  {id:'diarrhea',label:'Intestino solto',category:'intestino',aliases:['diarreia','fezes soltas'],weights:{spleen_qi:2,liver_spleen:2}},
  {id:'reflux',label:'Azia / refluxo',category:'digestao',aliases:['azia','refluxo','queimação'],weights:{liver_spleen:1,liver_stagnation:1}},
  {id:'cold',label:'Frio no corpo',category:'temperatura',aliases:['muito frio','mãos frias','pés frios'],weights:{kidney_yang:3,spleen_yang:2}},
  {id:'dizziness',label:'Tontura',category:'cabeca',aliases:['vertigem'],weights:{kidney_yin:1,liver_fire:1}},
  {id:'short_breath',label:'Falta de ar',category:'respiracao',aliases:['dispneia','fôlego curto'],weights:{lung_qi:3,kidney_receive_lung:2}},
  {id:'low_back',label:'Dor / fraqueza lombar',category:'dor',aliases:['lombalgia','dor lombar'],weights:{kidney_yang:2,kidney_yin:2,kidney_receive_lung:2}},

  {id:'tinnitus',label:'Zumbido',category:'cabeca',aliases:['zumbido no ouvido'],weights:{kidney_yin:3}},
  {id:'night_sweats',label:'Suor noturno',category:'temperatura',aliases:['suar à noite'],weights:{kidney_yin:3,heart_yin:2},contradicts:{kidney_yang:2}},
  {id:'dry_mouth',label:'Boca / garganta seca',category:'digestao',aliases:['boca seca','garganta seca','secura na boca'],weights:{kidney_yin:2,heart_yin:2}},
  {id:'clear_urine',label:'Urina clara e frequente',category:'urina',aliases:['urina clara','urino muito'],weights:{kidney_yang:3,kidney_receive_lung:2},contradicts:{kidney_yin:2}},
  {id:'weak_voice',label:'Voz fraca',category:'respiracao',aliases:['voz baixa'],weights:{lung_qi:3}},
  {id:'frequent_colds',label:'Resfriados frequentes',category:'respiracao',aliases:['gripo fácil'],weights:{lung_qi:3}},
  {id:'difficulty_inhaling',label:'Difícil puxar o ar para dentro',category:'respiracao',aliases:['dificuldade para inspirar'],weights:{kidney_receive_lung:4}},
  {id:'bitter_taste',label:'Gosto amargo',category:'digestao',aliases:['boca amarga'],weights:{liver_fire:3}},
  {id:'red_eyes',label:'Olhos vermelhos',category:'cabeca',aliases:['olhos avermelhados'],weights:{liver_fire:3}},
  {id:'red_face_eyes',label:'Face ou olhos muito vermelhos',category:'cabeca',aliases:['rosto vermelho','olhos muito vermelhos'],weights:{liver_fire:2,liver_yang_rising:1}},
  {id:'thirst',label:'Muita sede',category:'temperatura',aliases:['sede aumentada','muita sede'],weights:{liver_fire:2}},
  {id:'sighing',label:'Suspiro muito',category:'emocional',aliases:['suspiro frequente','suspiro muito'],weights:{liver_stagnation:3}},
  {id:'poor_appetite',label:'Pouco apetite',category:'digestao',aliases:['sem fome','falta de apetite'],weights:{spleen_qi:3,spleen_yang:2}},  {id:'stress_bowel',label:'Intestino piora com estresse',category:'intestino',aliases:['intestino nervoso'],weights:{liver_spleen:4}},
  {id:'better_after_bm',label:'Melhora depois de evacuar',category:'intestino',aliases:['melhora após evacuar'],weights:{liver_spleen:4}},  {id:'undigested_stool',label:'Alimento não digerido nas fezes',category:'intestino',aliases:['comida nas fezes'],weights:{spleen_yang:3,kidney_yang:1}},
  {id:'palpitations',label:'Palpitações',category:'peito',aliases:['coração acelerado','coração batendo forte'],weights:{heart_blood:2,heart_yin:2}},
  {id:'dreams',label:'Muitos sonhos / sono agitado',category:'sono',aliases:['muitos sonhos'],weights:{heart_blood:3,heart_yin:1}},
  {id:'restlessness',label:'Agitação à noite',category:'sono',aliases:['mente agitada à noite'],weights:{heart_yin:3}},
  {id:'memory',label:'Memória ruim',category:'cabeca',aliases:['esquecimento'],weights:{heart_blood:2,kidney_yin:1}},
  {id:'pale',label:'Palidez',category:'energia',aliases:['pálido'],weights:{heart_blood:3,spleen_qi:1,lung_qi:1}},
  {id:'sweating',label:'Suor fácil',category:'temperatura',aliases:['sudorese','suando muito'],weights:{heart_qi:2}},
  {id:'cold_limbs',label:'Mãos ou pés frios',category:'temperatura',aliases:['extremidades frias'],weights:{heart_yang:2,kidney_yang:2,spleen_yang:2}},
  {id:'heart_discomfort',label:'Desconforto na região do peito/coração',category:'peito',aliases:['desconforto no peito'],weights:{heart_yang:2}},
  {id:'bearing_down',label:'Sensação de peso para baixo no abdome',category:'digestao',aliases:['peso para baixo'],weights:{spleen_qi_sinking:3}},
  {id:'frequent_urine',label:'Urinar muitas vezes',category:'urina',aliases:['urina frequente'],weights:{spleen_qi_sinking:1}},
  {id:'bleeding_easy',label:'Sangramentos ou manchas roxas fáceis',category:'outros',aliases:['hematomas fáceis','sangramento fácil'],weights:{spleen_not_holding_blood:3}},
  {id:'burning_stomach',label:'Queimação no estômago',category:'digestao',aliases:['estômago queimando'],weights:{stomach_yin:2}},
  {id:'dry_stool',label:'Fezes muito secas',category:'intestino',aliases:['cocô seco','fezes ressecadas'],weights:{stomach_yin:2,large_intestine_heat:3}},
  {id:'bad_breath',label:'Mau hálito',category:'digestao',aliases:['bafo','hálito ruim'],weights:{large_intestine_heat:1}},
  {id:'dark_urine',label:'Urina escura e pouca',category:'urina',aliases:['urina escura','pouca urina'],weights:{large_intestine_heat:2,liver_fire:1}},
  {id:'belching',label:'Arrotos frequentes',category:'digestao',aliases:['arroto','eructação','arroto muito'],weights:{food_stagnation:2}},
  {id:'sour_reflux',label:'Regurgitação ácida / gosto azedo',category:'digestao',aliases:['gosto azedo','ácido na boca'],weights:{food_stagnation:2,liver_stagnation:1}},
  {id:'gas',label:'Gases',category:'digestao',aliases:['flatulência'],weights:{food_stagnation:2,liver_spleen:1}},
  {id:'nausea',label:'Náusea',category:'digestao',aliases:['enjoo'],weights:{food_stagnation:2,liver_stagnation:1}},

  {id:'worse_after_meals',label:'Piora depois de comer',category:'digestao',aliases:['piora após comer','depois da refeição'],weights:{spleen_qi:3}},
  {id:'worse_stress',label:'Piora quando fico estressado ou irritado',category:'emocional',aliases:['piora com estresse','piora nervoso']},
  {id:'better_warmth',label:'Melhora com calor',category:'temperatura',aliases:['melhora aquecendo','melhora quente','calor melhora'],weights:{spleen_yang:3,spleen_qi:1}},
  {id:'worse_raw_cold_food',label:'Piora com alimentos frios ou crus',category:'digestao',aliases:['piora com comida fria','piora com cru']},
  {id:'evening_worse',label:'Digestão / barriga piora no fim do dia ou à noite',category:'digestao',aliases:['piora à noite','piora no fim do dia']},
  {id:'difficulty_falling_asleep',label:'Tenho dificuldade para pegar no sono',category:'sono',aliases:['demoro para dormir']},
  {id:'frequent_waking',label:'Acordo várias vezes durante a noite',category:'sono',aliases:['acordo muito']},
  {id:'dream_disturbed',label:'Tenho muitos sonhos ou o sono fica agitado',category:'sono',aliases:['sonho muito','sono com sonhos']},
  {id:'waking_1_3',label:'Costumo acordar entre 1h e 3h',category:'sono',aliases:['acordo 1 da manhã','acordo 3 da manhã']},
  {id:'poor_memory',label:'Memória pior ou dificuldade para lembrar',category:'sono',aliases:['memória ruim','esquecimento','memória fraca']},
  {id:'five_center_heat',label:'Sensação de calor em mãos, pés ou peito',category:'temperatura',aliases:['calor nas mãos e pés']},
  {id:'temporal_headache',label:'Dor de cabeça nas têmporas',category:'cabeca',aliases:['dor nas têmporas','cefaleia temporal']},
  {id:'throbbing_headache',label:'Dor de cabeça pulsátil ou latejante',category:'cabeca',aliases:['dor latejante','pulsando']},
  {id:'dry_eyes',label:'Olhos secos',category:'cabeca',aliases:['secura nos olhos']},
  {id:'rib_pain',label:'Dor ou pressão na lateral das costelas',category:'dor',aliases:['dor nas costelas','dor no hipocôndrio']},
  {id:'acute_low_back',label:'A dor lombar começou de forma aguda',category:'dor',aliases:['lombalgia aguda','começou de repente']},
  {id:'low_back_cold_heavy',label:'A lombar parece fria, pesada ou dolorida',category:'dor',aliases:['lombar fria','lombar pesada']},
  {id:'worse_cold_rain',label:'Piora com frio, chuva ou umidade',category:'temperatura',aliases:['piora na chuva','piora com frio','frio e chuva pioram']},
  {id:'hot_swollen_back',label:'A lombar fica quente ou com sensação de inchaço',category:'dor',aliases:['lombar quente','lombar inchada']},
  {id:'worse_hot_humid',label:'Piora em clima quente e úmido',category:'temperatura',aliases:['piora no calor úmido']},
  {id:'fixed_piercing_back',label:'A dor é fixa, aguda ou perfurante',category:'dor',aliases:['dor fixa lombar','dor perfurante']},
  {id:'worse_pressure',label:'Piora quando aperto a região',category:'dor',aliases:['piora à pressão']},
  {id:'worse_evening',label:'Dor piora no fim do dia ou à noite',category:'dor',aliases:['piora à noite']},
  {id:'better_rest',label:'Melhora com repouso',category:'dor',aliases:['melhora descansando']},


  // High-information lay-observable findings from the book tables.
  {id:'mouth_ulcers',label:'Aftas / úlceras na boca',category:'boca',aliases:['aftas','feridas na boca','úlceras orais'],weights:{heart_fire:3,stomach_phlegm_fire:2}},
  {id:'bleeding_gums',label:'Gengiva inchada ou sangrando',category:'boca',aliases:['gengiva sangrando','gengiva inflamada'],weights:{stomach_fire:4,stomach_phlegm_fire:2}},
  {id:'constant_hunger',label:'Fome constante',category:'digestao',aliases:['muita fome','fome o tempo todo'],weights:{stomach_fire:3,stomach_phlegm_fire:2,stomach_yin:1,spleen_yin:1}},
  {id:'cold_drinks',label:'Sede com preferência por bebidas frias',category:'temperatura',aliases:['quero bebida gelada'],weights:{stomach_fire:3,lung_heat:2}},
  {id:'dry_cough',label:'Tosse seca',category:'respiracao',aliases:['tosse sem catarro'],weights:{lung_yin:3,lung_dryness:3}},
  {id:'yellow_phlegm',label:'Catarro amarelo ou verde',category:'respiracao',aliases:['catarro amarelo','catarro verde'],weights:{lung_phlegm_heat:4,lung_wind_heat:2}},
  {id:'white_watery_phlegm',label:'Catarro branco e aquoso',category:'respiracao',aliases:['catarro branco','catarro aguado'],weights:{lung_phlegm_cold:4,lung_phlegm_fluid:3}},
  {id:'dry_skin',label:'Pele seca',category:'pele',aliases:['ressecamento da pele'],weights:{lung_dryness:3,large_intestine_dryness:1}},
  {id:'hard_dry_stool',label:'Fezes muito duras e secas',category:'intestino',aliases:['fezes duras','cocô muito seco'],weights:{large_intestine_dryness:4,large_intestine_heat:2,stomach_yin:2}},
  {id:'burning_anus',label:'Ardor anal ao evacuar',category:'intestino',aliases:['queimação no ânus'],weights:{large_intestine_heat:3,large_intestine_damp_heat:3}},
  {id:'smelly_diarrhea_mucus',label:'Diarreia com odor forte e muco',category:'intestino',aliases:['diarreia com muco'],weights:{large_intestine_damp_heat:4}},
  {id:'watery_urgent_diarrhea',label:'Diarreia aquosa e urgente',category:'intestino',aliases:['diarreia aguada urgente'],weights:{large_intestine_cold:4}},
  {id:'weak_knees',label:'Fraqueza nos joelhos',category:'dor',aliases:['joelhos fracos'],weights:{kidney_qi:2,kidney_yang:2,kidney_essence:2,liver_kidney_yin:1}},
  {id:'low_libido',label:'Libido baixa',category:'sexual',aliases:['pouco desejo sexual'],weights:{kidney_yang:2,kidney_essence:2,kidney_yin_yang:2}},
  {id:'urinary_dribbling',label:'Gotejamento depois de urinar',category:'urina',aliases:['urina pingando depois'],weights:{kidney_qi_not_firm:4,kidney_qi:2}},
  {id:'red_cheeks',label:'Bochechas avermelhadas, principalmente à noite',category:'temperatura',aliases:['bochecha vermelha'],weights:{kidney_yin:2,kidney_yin_fire:3,heart_yin:2,lung_yin:1}},
  {id:'blurred_vision',label:'Visão borrada',category:'cabeca',aliases:['visão turva'],weights:{liver_blood:3,liver_yin:3,liver_kidney_yin:2}},
  {id:'muscle_cramps',label:'Câimbras musculares frequentes',category:'dor',aliases:['cãibras'],weights:{liver_blood:3}},
  {id:'brittle_nails',label:'Unhas frágeis ou quebradiças',category:'pele',aliases:['unhas quebradiças'],weights:{liver_blood:3}},
  {id:'yellow_discharge',label:'Corrimento amarelado com coceira',category:'reprodutivo',aliases:['corrimento amarelo'],weights:{liver_damp_heat:4}},
  {id:'mental_confusion',label:'Confusão mental importante',category:'cabeca',aliases:['mente confusa'],weights:{heart_phlegm_fire:3}},
  {id:'chest_pain_radiates_arm',label:'Dor no peito irradiando para o braço esquerdo',category:'seguranca',aliases:['dor no peito para braço']},


  // Cross-system discriminators from the reference book tables.
  {id:'loose_stools',label:'Fezes amolecidas',category:'intestino',aliases:['fezes moles']},
  {id:'nightmares',label:'Pesadelos frequentes',category:'sono',aliases:['muitos pesadelos']},
  {id:'fearful',label:'Medo ou sustos fáceis',category:'emocional',aliases:['assustado fácil','muito medo']},
  {id:'plum_pit',label:'Sensação de bolo na garganta',category:'garganta',aliases:['bolo na garganta','algo preso na garganta']},
  {id:'catches_colds',label:'Pega resfriados com facilidade',category:'respiracao',aliases:['resfria fácil']},
  {id:'day_sweats',label:'Suor fácil durante o dia',category:'liquidos',aliases:['suo fácil de dia']},
  {id:'cold_body',label:'Sensação de frio no corpo',category:'temperatura',aliases:['corpo frio']},
  {id:'edema',label:'Inchaço / edema',category:'liquidos',aliases:['retenção de líquido','inchado']},
  {id:'pale_face',label:'Palidez percebida',category:'geral',aliases:['rosto pálido']},
  {id:'irritable',label:'Irritabilidade',category:'emocional',aliases:['irritado','raiva fácil']},
  {id:'pms',label:'Sintomas importantes antes da menstruação',category:'reprodutivo',aliases:['tpm']},
  {id:'phlegm',label:'Catarro / fleuma frequente',category:'respiracao',aliases:['muito catarro']},
  {id:'anxiety',label:'Ansiedade / agitação',category:'emocional',aliases:['ansioso','agitado']},
  {id:'pain_fixed',label:'Dor fixa e bem localizada',category:'dor',aliases:['dor sempre no mesmo lugar']},
  {id:'dark_face',label:'Coloração facial mais escura ou arroxeada',category:'geral',aliases:['rosto escuro','arroxeado']},
  {id:'chest_pain',label:'Dor ou pressão no peito',category:'seguranca',aliases:['dor no peito','pressão no peito']},
  {id:'pain_worse_night',label:'Dor pior à noite',category:'dor',aliases:['dor piora de noite']},
  {id:'hot_chest',label:'Sensação de calor no peito',category:'temperatura',aliases:['peito quente']},
  {id:'varicose_veins',label:'Veias varicosas aparentes',category:'circulacao',aliases:['varizes']},
  {id:'cold_feet',label:'Pés e pernas frios',category:'temperatura',aliases:['pé frio','pernas frias']},


  // Additional lay-observable discriminators recovered from pain, neurologic,
  // cardiovascular and throat tables.
  {id:'joint_pain',label:'Dor nas articulações',category:'dor',aliases:['dor articular']},
  {id:'joint_swelling',label:'Articulação inchada',category:'dor',aliases:['junta inchada']},
  {id:'joint_red',label:'Articulação vermelha e quente',category:'dor',aliases:['junta vermelha']},
  {id:'restricted_movement',label:'Movimento da articulação limitado',category:'dor',aliases:['articulação dura']},
  {id:'pain_worse_cold',label:'Dor piora com frio',category:'temperatura',aliases:['frio piora a dor']},
  {id:'weak_limbs',label:'Fraqueza nos braços ou pernas',category:'geral',aliases:['membros fracos']},
  {id:'head_heavy',label:'Sensação de cabeça pesada',category:'cabeca',aliases:['cabeça pesada']},
  {id:'chest_fullness',label:'Aperto ou plenitude no peito',category:'peito',aliases:['peito cheio','opressão no peito']},
  {id:'depressed',label:'Humor deprimido',category:'emocional',aliases:['desanimado','depressivo']},
  {id:'numbness',label:'Dormência ou formigamento',category:'neurologico',aliases:['formigamento','dormência']},
  {id:'tremor',label:'Tremores',category:'neurologico',aliases:['mãos tremendo','tremedeira']},
  {id:'muscle_stiffness',label:'Rigidez muscular',category:'neurologico',aliases:['músculos rígidos']},
  {id:'slow_movement',label:'Movimentos mais lentos',category:'neurologico',aliases:['lentidão para se mover']},
  {id:'cold_sweat',label:'Suor frio',category:'seguranca',aliases:['suando frio']},
  {id:'pain_radiates_shoulder',label:'Dor no peito irradiando para ombro ou costas',category:'seguranca',aliases:['dor peito para ombro']},
  {id:'stress_worse',label:'Piora claramente com estresse',category:'emocional',aliases:['estresse piora']},
  {id:'sudden_onset',label:'Começou de forma súbita',category:'seguranca',aliases:['começou de repente']},
  {id:'facial_weakness',label:'Fraqueza ou queda de um lado do rosto',category:'seguranca',aliases:['rosto caído']},
  {id:'dry_throat',label:'Garganta seca',category:'garganta',aliases:['secura na garganta']},
  {id:'dark_phlegm',label:'Catarro escuro',category:'respiracao',aliases:['catarro marrom','catarro escuro']},


  // Urinary discriminators from Lin syndrome tables.
  {id:'burning_urine',label:'Ardor ou dor ao urinar',category:'urina',aliases:['ardência para urinar','dor ao urinar']},
  {id:'urinary_urgency',label:'Urgência para urinar',category:'urina',aliases:['vontade urgente de urinar']},
  {id:'blood_urine',label:'Sangue visível na urina',category:'seguranca',aliases:['urina com sangue']},
  {id:'blood_clots_urine',label:'Coágulos visíveis na urina',category:'seguranca',aliases:['coágulo na urina']},
  {id:'cloudy_urine',label:'Urina turva ou muito oleosa',category:'urina',aliases:['urina turva']},
  {id:'urinary_difficulty',label:'Dificuldade para urinar',category:'urina',aliases:['urina com dificuldade']},
  {id:'heavy_limbs',label:'Sensação de peso nas pernas ou braços',category:'geral',aliases:['membros pesados']},
  {id:'fever',label:'Febre',category:'seguranca',aliases:['estou com febre']},


  // Skin-disorder discriminators from the reference-book dermatology chapter.
  {id:'red_pimples',label:'Espinhas vermelhas e inflamadas',category:'pele',aliases:['espinhas vermelhas']},
  {id:'painful_pimples',label:'Espinhas doloridas',category:'pele',aliases:['acne dolorida']},
  {id:'large_inflamed_pimples',label:'Espinhas grandes e muito inflamadas',category:'pele',aliases:['espinhas grandes inflamadas']},
  {id:'pus_skin',label:'Lesões de pele com pus',category:'pele',aliases:['pus na pele']},
  {id:'pus_abscesses',label:'Abscessos dolorosos com pus',category:'pele',aliases:['abscesso com pus']},
  {id:'pale_eruptions',label:'Lesões de pele mais pálidas ou rosadas',category:'pele',aliases:['lesões pálidas']},
  {id:'oozing_skin',label:'Lesões que soltam líquido',category:'pele',aliases:['pele escorrendo líquido']},
  {id:'oily_skin',label:'Pele muito oleosa',category:'pele',aliases:['pele oleosa']},
  {id:'purple_scars',label:'Cicatrizes arroxeadas',category:'pele',aliases:['cicatriz roxa']},
  {id:'bleeding_pimples',label:'Espinhas que sangram com facilidade',category:'pele',aliases:['acne sangrando']},
  {id:'dark_lips_nails',label:'Lábios ou unhas arroxeados',category:'geral',aliases:['unhas roxas','lábios roxos']},
  {id:'red_nose',label:'Nariz persistentemente avermelhado',category:'pele',aliases:['nariz vermelho']},
  {id:'hot_skin',label:'Pele com sensação de calor',category:'pele',aliases:['pele quente']},
  {id:'thick_red_skin',label:'Pele avermelhada e espessada',category:'pele',aliases:['pele grossa e vermelha']},
  {id:'very_red_skin',label:'Pele muito avermelhada',category:'pele',aliases:['pele muito vermelha']},
  {id:'purple_skin',label:'Pele arroxeada',category:'pele',aliases:['pele roxa']},
  {id:'dry_scaly_rash',label:'Placas secas e descamativas',category:'pele',aliases:['pele descamando','placas secas']},
  {id:'rash_near_joints',label:'Lesões de pele próximas às articulações',category:'pele',aliases:['lesões perto das juntas']},
  {id:'rash_groin_axilla',label:'Lesões em axilas ou virilha',category:'pele',aliases:['lesões na axila','lesões na virilha']},
  {id:'worse_damp_weather',label:'Piora em dias úmidos',category:'ambiente',aliases:['umidade piora']},
  {id:'bloody_skin',label:'Lesões de pele com sangramento',category:'pele',aliases:['pele sangrando']},
  {id:'burning_skin',label:'Ardência ou queimação na pele',category:'pele',aliases:['pele queimando']},
  {id:'heartburn',label:'Queimação / azia',category:'digestao',aliases:['azia']},
  {id:'acid_reflux',label:'Refluxo ácido',category:'digestao',aliases:['refluxo']},
  {id:'allergies',label:'Alergias ambientais frequentes',category:'respiracao',aliases:['alergia ambiental']},
  {id:'cough_easy',label:'Tosse com facilidade',category:'respiracao',aliases:['tusso fácil']},


  // Digestive and gynecologic discriminators from constipation, amenorrhea and PMS tables.
  {id:'smelly_dry_stool',label:'Fezes secas com odor forte',category:'intestino',aliases:['fezes secas fedidas']},
  {id:'constipation_diarrhea_alternating',label:'Alterna intestino preso e diarreia',category:'intestino',aliases:['alterna prisão de ventre e diarreia']},
  {id:'incomplete_bowel',label:'Sensação de evacuação incompleta',category:'intestino',aliases:['parece que não terminou de evacuar']},
  {id:'mucus_stool',label:'Muco nas fezes',category:'intestino',aliases:['fezes com muco']},
  {id:'poor_concentration',label:'Dificuldade de concentração',category:'cabeca',aliases:['concentração ruim']},
  {id:'mood_swings',label:'Mudanças de humor',category:'emocional',aliases:['humor muda muito']},
  {id:'abdominal_pain',label:'Dor abdominal',category:'digestao',aliases:['dor na barriga']},
  {id:'sticky_vaginal_discharge',label:'Corrimento vaginal espesso ou pegajoso',category:'reprodutivo',aliases:['corrimento pegajoso']},
  {id:'breast_distension',label:'Mamas doloridas ou inchadas antes da menstruação',category:'reprodutivo',aliases:['seios inchados antes da menstruação']},
  {id:'breast_hardness',label:'Mamas endurecidas antes da menstruação',category:'reprodutivo',aliases:['seios duros antes da menstruação']},
  {id:'breast_nodules',label:'Nódulos mamários percebidos',category:'reprodutivo',aliases:['caroço na mama']},
  {id:'menstrual_clots',label:'Coágulos na menstruação',category:'reprodutivo',aliases:['menstruação com coágulos']},
  {id:'menstrual_cramps',label:'Cólicas menstruais',category:'reprodutivo',aliases:['cólica menstrual']},
  {id:'irregular_period',label:'Ciclo menstrual irregular',category:'reprodutivo',aliases:['menstruação irregular']},


  {id:'amenorrhea',label:'Menstruação ausente por alguns ciclos',category:'reprodutivo',aliases:['menstruação não vem','sem menstruar']},
  {id:'scanty_menses',label:'Fluxo menstrual muito pequeno',category:'reprodutivo',aliases:['menstruação pouca','pouco fluxo']},
  {id:'hot_flash',label:'Ondas de calor',category:'temperatura',aliases:['fogacho','calorão']},
  {id:'facial_pain',label:'Dor no rosto',category:'dor',aliases:['dor facial']},
  {id:'big_toe_pain',label:'Dor forte no dedão do pé',category:'dor',aliases:['dor no hálux','dor no dedão']},
  {id:'restless',label:'Inquietação importante',category:'emocional',aliases:['muito inquieto','agitação']},

  // Safety-only observations: never carry TCM weights.
  {id:'severe_chest_pain',label:'Dor forte ou pressão importante no peito',category:'seguranca',aliases:['dor forte no peito']},
  {id:'severe_breathlessness',label:'Falta de ar intensa ou piorando rapidamente',category:'seguranca',aliases:['muita falta de ar']},
  {id:'new_neuro_deficit',label:'Fraqueza súbita, fala alterada ou assimetria nova',category:'seguranca',aliases:['fraqueza de um lado','fala enrolada']},
  {id:'black_bloody_stool',label:'Sangue importante nas fezes ou fezes negras',category:'seguranca',aliases:['sangue nas fezes','fezes pretas']},
  {id:'syncope',label:'Desmaio',category:'seguranca',aliases:['desmaiei']},
  {id:'severe_sudden_headache',label:'Dor de cabeça súbita e muito intensa',category:'seguranca',aliases:['pior dor de cabeça da vida']},
  {id:'fever_severe_abdominal_pain',label:'Febre junto com dor abdominal importante',category:'seguranca',aliases:['febre e dor forte na barriga']},
  {id:'saddle_anesthesia_bladder',label:'Dormência íntima com dificuldade nova para urinar ou evacuar',category:'seguranca',aliases:['dormência entre as pernas']},
  {id:'unexplained_weight_loss',label:'Perda de peso sem explicação',category:'seguranca',aliases:['emagrecimento sem motivo']},
  {id:'persistent_fever',label:'Febre persistente',category:'seguranca',aliases:['febre há dias']},
  {id:'progressive_weakness',label:'Fraqueza que está piorando',category:'seguranca',aliases:['fraqueza progressiva']},
  {id:'persistent_vomiting',label:'Vômitos persistentes',category:'seguranca',aliases:['vomitando sem parar']},

  // v0.86 — high-information discriminators from the supplied structured lessons.
  // Kept lay-observable; pulse and tongue remain excluded.
  {id:'near_total_insomnia',label:'Quase não consigo dormir durante a noite',category:'sono',aliases:['não durmo nada','insônia quase total']},
  {id:'marked_agitation',label:'Agitação muito intensa',category:'emocional',aliases:['muito agitado','agitação extrema']},
  {id:'large_cold_gulps',label:'Quando tenho sede, bebo bastante líquido gelado de uma vez',category:'temperatura',aliases:['grandes goles de água gelada','bebo muita água gelada']},
  {id:'small_sips',label:'Tenho boca seca, mas prefiro beber em pequenos goles',category:'temperatura',aliases:['pequenos goles','bebo aos poucos']},
  {id:'early_morning_diarrhea',label:'Diarreia muito cedo pela manhã, perto de 5h',category:'intestino',aliases:['diarreia às 5h','diarreia de madrugada cedo']},
  {id:'low_pitch_tinnitus',label:'Zumbido de tom mais grave e contínuo',category:'cabeca',aliases:['zumbido grave','zumbido baixo']},
  {id:'fixed_nightmare_theme',label:'Pesadelos repetem o mesmo tema há muito tempo',category:'sono',aliases:['mesmo pesadelo sempre']},
  {id:'changing_nightmares',label:'Pesadelos frequentes mudam muito de tema',category:'sono',aliases:['pesadelos variados']},
  // v0.89 — discriminators needed to resolve explicit thermal differentials.
  {id:'clear_runny_nose',label:'Coriza clara e aquosa',category:'respiracao',aliases:['nariz escorrendo claro','coriza transparente'],weights:{lung_wind_cold:3}},
  {id:'strong_aversion_cold',label:'Aversão forte ao frio',category:'temperatura',aliases:['muito incômodo com frio','calafrio forte'],weights:{lung_wind_cold:3}},
  {id:'sore_throat',label:'Dor de garganta',category:'garganta',aliases:['garganta doendo','garganta inflamada'],weights:{lung_wind_heat:2}},
  {id:'thick_phlegm',label:'Catarro espesso e difícil de eliminar',category:'respiracao',aliases:['catarro grosso','fleuma espessa'],weights:{lung_phlegm_heat:2}},
  {id:'clear_phlegm',label:'Catarro claro ou esbranquiçado e fluido',category:'respiracao',aliases:['catarro claro','fleuma clara'],weights:{lung_phlegm_cold:2}},
  {id:'burning_stool',label:'Evacuação com sensação de ardor ou queimação',category:'intestino',aliases:['fezes queimando','ardor ao evacuar'],weights:{large_intestine_heat:2,large_intestine_damp_heat:2}},
  {id:'foul_stool',label:'Fezes ou diarreia com odor muito forte',category:'intestino',aliases:['fezes muito fétidas','diarreia fedida'],weights:{large_intestine_damp_heat:2,large_intestine_heat:1}},
  {id:'watery_stool',label:'Fezes muito aquosas',category:'intestino',aliases:['diarreia muito aguada'],weights:{large_intestine_cold:2}},
  {id:'worse_cold',label:'Os sintomas pioram claramente com frio',category:'temperatura',aliases:['frio piora','piora quando esfria'],weights:{large_intestine_cold:1,cold_invades_stomach:1,lung_wind_cold:1}},

  // v0.90 — structure/function coexistence discriminators for chronic Kidney deficiency.
  {id:'premature_grey_hair',label:'Cabelos embranqueceram precocemente ou aumentaram muito com o tempo',category:'outros',aliases:['cabelos brancos cedo','embranquecimento precoce'],weights:{kidney_essence:2,kidney_yin:1}},
  {id:'sexual_function_low',label:'Redução importante da função sexual ou dificuldade de ereção',category:'outros',aliases:['impotência','disfunção erétil','função sexual baixa'],weights:{kidney_yang:2,kidney_qi:1}},
  {id:'urination_changed',label:'Alteração persistente da micção',category:'urinario',aliases:['mudança para urinar','alteração urinária'],weights:{kidney_qi:1,kidney_yang:1}},
]

export const primarySymptomIds = [
  'bloating','fatigue','poor_sleep','stress','headache','constipation',
  'diarrhea','reflux','cold','dizziness','short_breath','low_back'
]
