export type KnowledgeTopicId='wood'|'fire'|'earth'|'metal'|'water'|'yin_yang'|'qi'|'tao'|'wuxing'
export type KnowledgeTopic={id:KnowledgeTopicId;title:string;chinese?:string;subtitle:string;intro:string;facts:Array<{label:string;value:string}>;sections:Array<{title:string;body:string}>}

export const knowledgeTopics:Record<KnowledgeTopicId,KnowledgeTopic>={
wood:{id:'wood',title:'Madeira',chinese:'木 · Mù',subtitle:'Nascer, crescer, direcionar-se',intro:'Madeira representa o movimento de expansão da vida: o broto que rompe a terra, cresce, procura luz e encontra direção.',facts:[
{label:'Órgãos',value:'Fígado · Vesícula Biliar'},{label:'Estação',value:'Primavera'},{label:'Direção',value:'Leste'},{label:'Cor',value:'Verde'},{label:'Emoção',value:'Raiva · irritação · impulso'},{label:'Espírito',value:'Hun'},{label:'Sabor',value:'Ácido / azedo'},{label:'Som',value:'Grito / voz projetada'},{label:'Nota tradicional',value:'Jue (角)'},{label:'Clima',value:'Vento'},{label:'Sentido',value:'Olhos'},{label:'Tecido',value:'Tendões'},{label:'Horário dos canais',value:'VB 23–1h · F 1–3h'},{label:'Ciclo da vida',value:'Nascimento, infância e crescimento — leitura simbólica'}],sections:[
{title:'O movimento da Madeira',body:'É a força que inicia, cresce, planeja e procura passagem. Na linguagem tradicional, o Fígado favorece o livre fluxo do Qi e a Vesícula Biliar se relaciona à decisão e direção.'},{title:'Emoção e movimento',body:'A raiva pertence à Madeira. Em equilíbrio, pode ser lida como capacidade de mobilização, afirmação e mudança; quando o movimento fica bloqueado, frustração e irritabilidade podem ganhar destaque.'},{title:'Na natureza',body:'Primavera, brotação, vento, verde e movimento ascendente expressam a imagem da Madeira.'}]},

fire:{id:'fire',title:'Fogo',chinese:'火 · Huǒ',subtitle:'Aquecer, expandir, comunicar',intro:'Fogo é o movimento de máxima expansão: calor, luminosidade, contato e expressão. É o verão da vida, quando aquilo que cresceu se manifesta plenamente.',facts:[
{label:'Órgãos',value:'Coração · Intestino Delgado'},{label:'Estação',value:'Verão'},{label:'Direção',value:'Sul'},{label:'Cor',value:'Vermelho'},{label:'Emoção',value:'Alegria'},{label:'Espírito',value:'Shen'},{label:'Sabor',value:'Amargo'},{label:'Som',value:'Riso'},{label:'Nota tradicional',value:'Zhi (徵)'},{label:'Clima',value:'Calor'},{label:'Sentido',value:'Língua'},{label:'Tecido',value:'Vasos sanguíneos'},{label:'Horário dos canais',value:'C 11–13h · ID 13–15h'},{label:'Ciclo da vida',value:'Juventude, expressão e auge — leitura simbólica'}],sections:[
{title:'O movimento do Fogo',body:'O Fogo sobe, aquece e irradia. Na Medicina Chinesa, o Coração abriga o Shen e ocupa um lugar central na integração da vida mental e afetiva.'},{title:'Alegria e presença',body:'A alegria corresponde ao Fogo. A imagem equilibrada é calor humano, presença, comunicação e conexão; a mesma esfera pode aparecer desorganizada como agitação ou excitação excessiva.'},{title:'Água e Fogo',body:'Água e Fogo formam um eixo essencial. A base Yin ajuda a conter e refrescar; o Fogo aquece e movimenta. No motor clínico, porém, cada desequilíbrio continua independente e precisa de sintomas próprios.'}]},

earth:{id:'earth',title:'Terra',chinese:'土 · Tǔ',subtitle:'Nutrir, transformar, sustentar',intro:'Terra é centro. Recebe, transforma e distribui. É a imagem do solo que acolhe e converte aquilo que chega em nutrição.',facts:[
{label:'Órgãos',value:'Baço · Estômago'},{label:'Estação',value:'Fim do verão / transições'},{label:'Direção',value:'Centro'},{label:'Cor',value:'Amarelo'},{label:'Emoção',value:'Preocupação · reflexão'},{label:'Espírito',value:'Yi'},{label:'Sabor',value:'Doce'},{label:'Som',value:'Canto'},{label:'Nota tradicional',value:'Gong (宮)'},{label:'Clima',value:'Umidade'},{label:'Sentido',value:'Boca'},{label:'Tecido',value:'Músculos / carne'},{label:'Horário dos canais',value:'E 7–9h · BP 9–11h'},{label:'Ciclo da vida',value:'Maturidade, nutrição e centro — leitura simbólica'}],sections:[
{title:'O movimento da Terra',body:'Terra transforma alimento e experiência em algo utilizável. Baço e Estômago representam, na linguagem tradicional, uma grande parte da produção pós-natal de Qi e Sangue.'},{title:'Pensar e ruminar',body:'Yi envolve pensamento, intenção e concentração. A preocupação pertence a essa esfera; a imagem do desequilíbrio é o pensamento que deixa de processar e começa a girar em torno de si mesmo.'},{title:'Na natureza',body:'Solo, colheita, umidade, centro e transição expressam a capacidade de receber e sustentar.'}]},

metal:{id:'metal',title:'Metal',chinese:'金 · Jīn',subtitle:'Condensar, organizar, deixar ir',intro:'Metal é o movimento de recolhimento. Depois da expansão, a vida seleciona, estrutura e solta o que já cumpriu seu ciclo.',facts:[
{label:'Órgãos',value:'Pulmão · Intestino Grosso'},{label:'Estação',value:'Outono'},{label:'Direção',value:'Oeste'},{label:'Cor',value:'Branco'},{label:'Emoção',value:'Tristeza · pesar'},{label:'Espírito',value:'Po'},{label:'Sabor',value:'Picante / pungente'},{label:'Som',value:'Choro'},{label:'Nota tradicional',value:'Shang (商)'},{label:'Clima',value:'Secura'},{label:'Sentido',value:'Nariz'},{label:'Tecido',value:'Pele e pelos'},{label:'Horário dos canais',value:'P 3–5h · IG 5–7h'},{label:'Ciclo da vida',value:'Maturidade tardia, colheita e desapego — leitura simbólica'}],sections:[
{title:'O movimento do Metal',body:'Metal condensa e dá contorno. O Pulmão se relaciona ao Qi e à respiração; o Intestino Grosso oferece uma imagem complementar de eliminação e liberação.'},{title:'Tristeza e desapego',body:'A tristeza pertence ao Metal. Ela não é tratada aqui como doença, mas como uma correspondência tradicional ligada ao recolhimento, à perda e à capacidade de deixar ir.'},{title:'Na natureza',body:'Outono, secura, queda das folhas, condensação e definição traduzem o movimento do Metal.'}]},

water:{id:'water',title:'Água',chinese:'水 · Shuǐ',subtitle:'Armazenar, aprofundar, preservar',intro:'Água é profundidade e reserva. No inverno, a vida não desaparece: recolhe-se, conserva potencial e prepara um novo começo.',facts:[
{label:'Órgãos',value:'Rim · Bexiga'},{label:'Estação',value:'Inverno'},{label:'Direção',value:'Norte'},{label:'Cor',value:'Preto / azul profundo'},{label:'Emoção',value:'Medo'},{label:'Espírito',value:'Zhi'},{label:'Sabor',value:'Salgado'},{label:'Som',value:'Gemido'},{label:'Nota tradicional',value:'Yu (羽)'},{label:'Clima',value:'Frio'},{label:'Sentido',value:'Ouvidos'},{label:'Tecido',value:'Ossos / medula'},{label:'Horário dos canais',value:'B 15–17h · R 17–19h'},{label:'Ciclo da vida',value:'Velhice, recolhimento e potencial de renascimento — leitura simbólica'}],sections:[
{title:'O movimento da Água',body:'Água desce, armazena e conserva. O Rim se relaciona tradicionalmente ao Jing, crescimento, desenvolvimento, reprodução, ossos, medula e à raiz do Yin e do Yang do organismo.'},{title:'A raiz do Yin e do Yang',body:'Na fisiologia tradicional, Yin e Yang do Rim oferecem uma base para Yin e Yang dos demais órgãos. Isso explica relações possíveis entre padrões, mas não cria diagnósticos automaticamente: cada desequilíbrio precisa dos seus próprios sintomas.'},{title:'Medo e vontade',body:'O medo corresponde à Água; Zhi representa vontade e determinação. Profundidade, reserva e capacidade de atravessar períodos de incerteza pertencem à sua imagem simbólica.'}]},

yin_yang:{id:'yin_yang',title:'Yin e Yang',chinese:'陰陽',subtitle:'O movimento dos opostos complementares',intro:'Yin e Yang não são coisas separadas. São maneiras relativas de descrever polaridades que dependem uma da outra e se transformam continuamente.',facts:[
{label:'Yin',value:'Interior · repouso · frio · substância · nutrição · recolhimento'},{label:'Yang',value:'Exterior · atividade · calor · função · transformação · expansão'},{label:'Princípio',value:'Cada polo contém a possibilidade do outro'},{label:'Movimento',value:'Crescem, diminuem, restringem-se e transformam-se mutuamente'}],sections:[
{title:'Nunca absolutos',body:'Algo só é Yin ou Yang em relação a outra coisa. O interior é Yin em relação ao exterior; dentro do próprio interior ainda existem aspectos mais Yin e mais Yang.'},{title:'Desequilíbrio não é exclusão',body:'Deficiência de Yin e Deficiência de Yang podem coexistir. Uma deficiência de Yin também pode coexistir com Yang ascendente ou manifestações de Calor/Fogo. O aplicativo mantém cada padrão independente e exige sintomas próprios para cada um.'},{title:'O símbolo vivo',body:'Os pontos opostos dentro do Taijitu lembram que nenhum polo é absolutamente puro. O movimento contínuo do núcleo 3D representa transformação, e não uma divisão rígida.'}]},

qi:{id:'qi',title:'Qi',chinese:'氣 · Qì',subtitle:'Movimento, transformação e vitalidade',intro:'Qi é uma das ideias centrais do pensamento e da Medicina Chinesa. Em linguagem tradicional, descreve atividade, movimento, transformação e vitalidade.',facts:[
{label:'Imagem',value:'Movimento que anima e transforma'},{label:'No corpo',value:'Mover · aquecer · transformar · proteger · conter'},{label:'No cosmos',value:'Processo de transformação dos fenômenos'},{label:'No aplicativo',value:'Metáfora visual nas linhas douradas'}],sections:[
{title:'Mais do que “energia”',body:'Traduzir Qi apenas como energia é útil como primeira aproximação, mas simplifica o conceito. Qi também descreve função, dinâmica, influência e transformação.'},{title:'Qi no organismo',body:'A Medicina Chinesa descreve diferentes manifestações do Qi conforme origem e função. O aplicativo apresenta essa linguagem como modelo tradicional, não como uma grandeza física mensurável.'},{title:'As linhas douradas',body:'No átomo Wu Xing, as linhas luminosas são uma metáfora para circulação e transformação. Elas não representam medição clínica nem fluxo anatômico literal.'}]},

tao:{id:'tao',title:'Tao',chinese:'道 · Dào',subtitle:'O caminho e o processo',intro:'Tao pode ser traduzido como caminho ou via. No pensamento chinês, aponta para a ordem e o processo pelos quais a natureza acontece e se transforma.',facts:[
{label:'Ideia',value:'Caminho · processo · ordem natural'},{label:'Relação',value:'Yin–Yang e Wu Xing descrevem modos de transformação dentro dessa visão'}],sections:[
{title:'Maior que a medicina',body:'Tao não é um diagnóstico médico. É uma ideia filosófica muito mais ampla, presente em diferentes tradições chinesas.'},{title:'No aplicativo',body:'Esta seção funciona como uma porta de entrada cultural e filosófica, separada do motor clínico.'}]},

wuxing:{id:'wuxing',title:'Wu Xing',chinese:'五行 · Wǔ Xíng',subtitle:'Cinco movimentos, não cinco caixas',intro:'Wu Xing organiza Madeira, Fogo, Terra, Metal e Água como fases ou movimentos relacionados. O valor do modelo está nas transformações e correspondências entre natureza, corpo e experiência.',facts:[
{label:'Madeira',value:'Crescer'},{label:'Fogo',value:'Expandir'},{label:'Terra',value:'Transformar e sustentar'},{label:'Metal',value:'Condensar e organizar'},{label:'Água',value:'Armazenar e preservar'}],sections:[
{title:'Um mapa de correspondências',body:'Órgãos, estações, cores, emoções, sabores, sons e direções foram organizados tradicionalmente em cinco grandes famílias de correspondência.'},{title:'Movimento',body:'Madeira alimenta Fogo; Fogo gera Terra; Terra se relaciona ao Metal; Metal à Água; Água nutre Madeira. Há também relações tradicionais de regulação. No aplicativo, elas ficam discretas para não transformar a experiência principal em um diagrama técnico.'},{title:'Não é uma anatomia',body:'Wu Xing é apresentado como uma estrutura tradicional de interpretação. As correspondências não equivalem a relações anatômicas ou fisiológicas biomédicas literais.'}]}
}
